### ISSUE TITLE
TypeScript files (*.ts) are categorized as binary files and are ignored

### ISSUE THREAD

**Issue by prabhjyotsingh** [jvz/sbt-rat#11]
This is resolved with https://issues.apache.org/jira/browse/RAT-234. I believe we need to bump up the version of "org.apache.rat" % "apache-rat-core" to "0.13"

**Comment by jvz** [comment]
Oh, I didn't even notice a new release of rat. I can make an update to this with that, thanks!

**Comment by jvz** [comment]
Fixed in 0.6.1.
